### ISSUE TITLE
Process *.vue throws exception

### ISSUE THREAD

**Issue by Darkbish** [lc60005457/parcel-plugin-vue#10]
I have a vue single file looks like:
```
<template>
  <form ref="form"
        class="el-form"
        :class="labelClass"
        @submit.prevent="submit">
    <slot></slot>
  </form>
</template>
<script>
export default {
  name: 'ElForm',
  componentName: 'ElForm',
  provide() {
    return {
      elForm: this,
    }
  },
  ...
}
</script>
```
The file folked from [ElementUI](https://github.com/ElemeFE/element/blob/dev/packages/form/src/form.vue), I added some custom methods to it.

Webpack succeed to process it, but parcel throws exception:
```
d:\Works\xt-static\src\components\Form.vue:4:0: 'import' and 'export' may only appear at the top level (4:0)
  2 |   <form ref="form"
  3 |         class="el-form"
> 4 |         :class="labelClass"
    | ^
  5 |         @submit.prevent="submit">
  6 |     <slot></slot>
  7 |   </form>
```
How do i fix it?

**Comment by BoltDoggy** [comment]
You can show a repo, I will test it. @Darkbish

**Comment by Darkbish** [comment]
Sorry for waiting a long time, there was some work to do yestoday.
Repo [parcel-demo](https://github.com/Darkbish/parcel-demo) for testing, @lc60005457 .
thanks!

**Comment by Darkbish** [comment]
I found the reason, `parcel-plugin-vue` does not support `eslint`, I should use `parcel-plugin-eslint`, you can close this issue, @lc60005457 .

**Comment by BoltDoggy** [comment]
@Darkbish No, not eslint Error.

in '.babelrc'

```js
{
  "presets": [
    [
      "env",
      {
        "modules": false // Here is murderer.
      },
      ...
    ]
  ],
  ...
}
```

`"modules": false` will tell babel not to transform 'import and export', my vue compiler throw this Error.

If you need `"modules": false`, like parcel-bundler used a 'babel-plugin-transform-es2015-modules-commonjs', you can edit '.babelrc'

```js
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": ["> 1%", "last 2 versions", "ie > 9"]
        }
      }
    ]
  ],
  "plugins": [
    "babel-plugin-transform-es2015-modules-commonjs", // add this line
    ...
  ]
}

```

**Comment by Darkbish** [comment]
Build success. But new issue occured, when I open the address in browser, the console printed
```
Error: Cannot find module 'babel-runtime/core-js/symbol/to-string-tag'
```
`webpack` use `"module": false` for `tree shaking`, does `parcel` support this feature?

**Comment by BoltDoggy** [comment]
@Darkbish Parcel looks like not support`tree shaking`, just I thinking.

You can ask parcel developers for right answers, and I will try to do compatibility.

---

```
Error: Cannot find module 'babel-runtime/core-js/symbol/to-string-tag'
```

Try to remove 'parcel-plugin-vue', then test it, Error also.

```js
{
  ...
  "plugins": [
      "transform-runtime", // Here is murderer.
  ]
}
```

Need parcel support.

https://github.com/parcel-bundler/parcel/issues/408

**Comment by Darkbish** [comment]
emm, `Parcel` does not seem suitable for development right now, back to `webpack`.
Thanks @lc60005457

**Comment by BoltDoggy** [comment]
It is not be unsuited to prod env just now.

But Parcel is developing rapidly, It will be better.
