### ISSUE TITLE
Hot Reload stop worked in html files

### ISSUE THREAD

**Issue by Leolik** [lc60005457/parcel-plugin-vue#12]
<!- description ->

Hot Reload stop worked in html files if parcel-plugin-vue used.
You may reproduce this bug in your parcel-vue-demo. If change vue file - hmr work fine, browser reloaded. but if you try change index.html (add h1 tag with text in body, for example) - browser not reloaded ((
For example, in https://github.com/parcel-bundler/examples with vue as js file - hmr in html worked fine.

<!- repo url ->

Show a repo url: https://github.com/lc60005457/parcel-vue-demo

<!- environment ->

| Software          | Version(s) |
| ----------------- | ---------- |
| parcel-plugin-vue | 1.4.0
| Parcel            | 1.3.1
| Vue               | 2.5.13
| Node              | v9.3.0
| npm/Yarn          | 5.5.1
| Operating System  | Ubuntu 16.04

**Comment by BoltDoggy** [comment]
I published `parcel-plugin-vue@1.5.0`, that will be fixed.
@Leolik

**Comment by Leolik** [comment]
Work like a charm! thx
