### ISSUE TITLE
.vue file can not be hot update

### ISSUE THREAD

**Issue by JZLeung** [lc60005457/parcel-plugin-vue#2]
when i change the .vue file, my browser doesn't auto reload the page.
but when i change the entry.js, it will auto reload.

**Comment by BoltDoggy** [comment]
@JZLeung Thank you for this.

I published the 'parcel-plugin-vue@1.2.0'.

**Comment by JZLeung** [comment]
@lc60005457 
I already update to version 1.3.0, it does make hot updates.
