### ISSUE TITLE
Update the example to include other required files?

### ISSUE THREAD

**Issue by tjk** [lc60005457/parcel-plugin-vue#6]
Would be nice to have minimal `package*`, `.babelrc`, etc. file in there?

----

As a side note, while trying to use this I get:

```
Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/c9e91b24666c1a67fcbdfea3f2ce2189.vue') is not a valid name.
```

**Comment by BoltDoggy** [comment]
@tjk 
The example is using the 'node_modules' of the 'parcel-plugin-vue'.

I run `npm run test` to parcel the example, so I can't add the 'package.json' for that.

If you need a full example, you can come here:

https://github.com/lc60005457/parcel-vue-demo

I will add `.babelrc`, etc. file here.

-----

And  if error also, can you show a repo with all codes?

**Comment by tjk** [comment]
@lc60005457 ~~it looks like the problem was because a `<script>` section was missing... IIRC that works in vue... I haven't looking into parcel or vue-template-compiler enough, maybe that doesn't make sense for parcel?~~

Hm, never mind. I've removed the `<script>` section and it works (even after restarting parcel). Not sure what was wrong.
