### ISSUE TITLE
Problem while importing modules

### ISSUE THREAD

**Issue by samundrak** [lc60005457/parcel-plugin-vue#9]
There seems some problem while importing node modules in .vue file.
i imported a small module and there was some error on console like `module id 15 not found`
though importing module on react app was working well.
Also importing css in js file was throwing error

**Comment by lc60005457** [comment]
You should show your all code or repo url.

**Comment by BoltDoggy** [comment]
@samundrak
You should show your all code or repo url.

**Comment by samundrak** [comment]
This is my repo https://github.com/samundrak/parceljs-example-vue-and-reactjs.
You can import module inside SFC script section.
can try with `import uuid from 'uuid'`

**Comment by BoltDoggy** [comment]
@samundrak  Waiting for https://github.com/parcel-bundler/parcel/issues/294

The reason is your react.html or children bundled the 'uuid'.

If vue.html only, it's normal.
